### ISSUE TITLE
dfxml dependency missing

### ISSUE THREAD

**Issue by sromkey** [timothyryanwalsh/cca-diskimageprocessor#18]
This line:

https://github.com/timothyryanwalsh/cca-diskimageprocessor/blob/master/diskimageanalyzer.py#L26

assumes dfxml tools are installed I think- how do I install them?

The error I'm seeing when trying to analyse is:

Traceback (most recent call last):
  File "/usr/share/ccatools/diskimageprocessor/diskimageanalyzer.py", line 26, in <module>
    import Objects
ImportError: No module named 'Objects'

**Comment by tw4l** [comment]
Hi Sarah,

Yes, it does! Because the tool assumes you're working within BitCurator (maybe not a fair assumption to make, but the one I was designing for).

Otherwise, you'll need to copy the contents of [Simson Garfinkel's DFXML libraries](https://github.com/simsong/dfxml) into /usr/share/dfxml, so that the path being imported in [line 25](https://github.com/timothyryanwalsh/cca-diskimageprocessor/blob/master/diskimageanalyzer.py#L25) is valid.

Other dependencies if using outside of BitCurator include:

* HFSExplorer (the latest snapshot version that fixed a previous bug with the CLI - see the [Brunnhilde](https://github.com/timothyryanwalsh/brunnhilde) repo for more info 
* tsk_recover
* Brunnhilde
* fiwalk
* md5deep
* bagit-python (optional)
* bulk_extractor (optional)

You can see why using it in BitCurator is a bit easier :) But I'm happy to document all this if you see other use cases!

**Comment by sromkey** [comment]
Ahhh I see! This explains my other issue that I filed as well, thanks for the help Tim.

**Comment by tw4l** [comment]
FYI, if you just want the outputs of the Analysis mode, you can also just use this script: https://github.com/timothyryanwalsh/cca-diskimageprocessor/blob/master/diskimageanalyzer.py

Doesn't need to be called from the GUI :)

**Comment by tw4l** [comment]
Hi Sarah - After hearing Shira and Susan's presentation at the BitCurator User Forum and thinking about it a bit, I think you could probably get the desired functionality from a way pared down version of the script (running it as-is will be slow, especially because it calls bulk extractor on every disk). If you or one of the devs wanna talk about it, feel free to drop me a line!
